version: '3'

services:

  jenkins:
    container_name: jenkins
    build: .
    restart: always
    ports: 
      - 8080:8080
      - 50000:50000
    expose: 
      - 8080
      - 50000
    volumes: 
      - jenkins_home:/var/jenkins_home